import { motion } from "framer-motion";

export const Panel = ({ children, className = "" }) => <div className={`rounded-2xl border border-white/10 bg-white/[0.035] shadow-2xl shadow-black/10 ${className}`}>{children}</div>;
export const PageHeader = ({ title, subtitle, actions }) => <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-orange-400">Admin console</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{actions}</div>;
export const StatCard = ({ label, value, detail, icon: Icon, tone = "orange" }) => <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/[.07] to-transparent p-5"><div className="flex items-center justify-between"><p className="text-sm text-slate-400">{label}</p>{Icon && <Icon className={`h-5 w-5 text-${tone}-400`} />}</div><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></motion.div>;
export const Button = ({ children, variant = "primary", className = "", ...props }) => <button className={`${variant === "primary" ? "bg-orange-500 text-white hover:bg-orange-400" : variant === "danger" ? "bg-red-500/10 text-red-400 hover:bg-red-500/20" : "border border-white/10 bg-white/5 text-slate-200 hover:bg-white/10"} rounded-xl px-4 py-2 text-sm font-medium transition disabled:opacity-40 ${className}`} {...props}>{children}</button>;
export const Input = (props) => <input {...props} className={`rounded-xl border border-white/10 bg-black/20 px-4 py-2.5 text-sm text-white outline-none placeholder:text-slate-600 focus:border-orange-500/50 ${props.className || ""}`} />;
export const Badge = ({ children, tone = "slate" }) => <span className={`inline-flex rounded-full bg-${tone}-500/10 px-2.5 py-1 text-xs font-medium text-${tone}-400`}>{children}</span>;
export const Empty = ({ children = "Nothing to show yet." }) => <div className="p-12 text-center text-sm text-slate-500">{children}</div>;
export const formatDate = (value) => value?.toDate ? value.toDate().toLocaleDateString() : "—";
